

package com.aslidongez.project.mernis;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.0.1.0
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: 0748CD85B25D51C6FB45A167F04462481585527E8FFF12036564B5056076309C431C9A20873A9D95B1835FF2CB0A84FB700607F7A17B1F35639B054DB5E67615
//------------------------------------------------------------------------

public class QLMSoapException extends java.lang.Exception
{
    private org.w3c.dom.Element _details=null;
    private Object _fault = null;
    
    public QLMSoapException(String message,org.w3c.dom.Element details)
    {
        super(message);
        _details=details;
    }

    public QLMSoapException(Object fault)
    {
        _fault=fault;
    }

    public Object getFault() {
        return _fault;
    }


    public org.w3c.dom.Element getDetails() {
        return _details;
    }
}